// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeg0n5evps5TeHLRpQLXzODHZke1D0WBs',
    appId: '1:775735976598:web:8153fd768a27d33d3958b7',
    messagingSenderId: '775735976598',
    projectId: 'roboo-db725',
    authDomain: 'roboo-db725.firebaseapp.com',
    storageBucket: 'roboo-db725.firebasestorage.app',
    measurementId: 'G-X1F07M94T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0mC8L5xJwWFexuyflcu0FfYQ1kpNzc6M',
    appId: '1:775735976598:android:ec5b55d94ce426c63958b7',
    messagingSenderId: '775735976598',
    projectId: 'roboo-db725',
    storageBucket: 'roboo-db725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWf34CixTs6-COZHZsT3JYVuumaeswGt8',
    appId: '1:775735976598:ios:e2d9eac9d50ace783958b7',
    messagingSenderId: '775735976598',
    projectId: 'roboo-db725',
    storageBucket: 'roboo-db725.firebasestorage.app',
    iosBundleId: 'sy.techtoc.roboo',
  );
}
